version: '3.9'
services:
  backend:
    container_name: backend
    build: ./todo-list_backend
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    working_dir: /todo-list_backend
    command: dev

    environment:
      API_PORT: 3000
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: database
      MYSQL_DATABASE: todo_list

  frontend:
    container_name: frontend
    build: ./todo-list_frontend
    ports:
      - "8080:8080"
    env_file:
      - .env

  database:
    image: mysql:8.0.32
    container_name: database
    ports:
      - "3306:3306"
    environment:
      API_PORT: 3000
      MYSQL_PASSWORD: password
      MYSQL_HOST: database
      MYSQL_DATABASE: todo_list
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5