version: '3.9'
services:
  backend:
    container_name: backend
    build: ./todo-list_backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - .env
    environment:
      API_PORT: 3000
      MYSQL_USER: root
      # MYSQL_PASSWORD: password
      MYSQL_HOST: database
      MYSQL_DATABASE: todo_list
      MYSQL_ROOT_PASSWORD: password

  frontend:
    container_name: frontend
    build: ./todo-list_frontend
    ports:
      - "8080:8080"
    env_file:
      - .env

  database:
    image: mysql:8.0.29
    container_name: database
    ports:
      - "3306:3306"
    environment:
      API_PORT: 3000
      # MYSQL_USER: root
      # MYSQL_PASSWORD: password
      MYSQL_HOST: database
      MYSQL_DATABASE: todo_list
      MYSQL_ROOT_PASSWORD: root_password