version: '3.9'
services:
  backend:
    container_name: backend
    build: ./todo-list_backend
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    working_dir: /todo-list_backend
    command: dev
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
    environment:
      API_PORT: ${API_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
      - .env

  frontend:
    container_name: frontend
    build: ./todo-list_frontend
    working_dir: /todo-list_frontend
    ports:
      - "8080:8080"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:8080"]
      timeout: 10s
      retries: 5
    depends_on:
      backend:
        condition: service_healthy 

  database:
    image: mysql:8.0.32
    container_name: database
    ports:
      - "3306:3306"
    environment:
      API_PORT: ${API_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5